name: Build & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run setup-self-contained
      - run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            npm run dist:win
          elif [ "${{ runner.os }}" = "Linux" ]; then
            npm run dist:linux
          elif [ "${{ runner.os }}" = "macOS" ]; then
            npm run dist:mac
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Read update log
        id: updatelog
        run: |
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          cat updata_log.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist-electron/BetterKugou-*.exe
            dist-electron/BetterKugou-*.AppImage
            dist-electron/BetterKugou-*.deb
            dist-electron/BetterKugou-*.rpm
            dist-electron/BetterKugou-*.dmg
            dist-electron/BetterKugou-*.zip
          body_path: updata_log.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
